// Code generated by kubectl-plugin-builder; DO NOT EDIT.

package subcmd

import (
        "github.com/spf13/cobra"

        "k8s.io/cli-runtime/pkg/genericclioptions"
)

var (
        subcmdflag1Flag string
)

// WARNING: don't rename this function.
func NewCommand(streams *genericclioptions.IOStreams) *cobra.Command {
        c := &cobra.Command{
                Use:  "subcmd",
                Short: "short description",
                Long: "long description",
                RunE: func(cmd *cobra.Command, args []string) error {
                        o := &options{streams: streams}
                        if err := o.Complete(cmd, args); err != nil {
                                return err
                        }

                        if err := o.Validate(); err != nil {
                                return err
                        }

                        return o.Run()
                },
        }
        c.Flags().StringVar(
                &subcmdflag1Flag,
                "flag1",
                "",
                "controls the subcmd's behavior",
        )

        return c
}
