// Code generated by kubectl-plugin-builder.

package subcmd

import (
        "fmt"

        "github.com/Drumato/kubectl-sample/internal/cmd"
        "github.com/spf13/cobra"
        "k8s.io/cli-runtime/pkg/genericclioptions"
)

var _ cmd.CLINodeOptions = &options{}
type options struct {
        cmd     *cobra.Command
        args    []string
        streams *genericclioptions.IOStreams
}

// Complete implements CLINodeOptions interface.
func (o *options) Complete(cmd *cobra.Command, args []string) error {
        o.cmd = cmd
        o.args = args
        return nil
}

// Validate implements CLINodeOptions interface.
func (o *options) Validate() error {
        return nil
}

// Run implements CLINodeOptions interface.
func (o *options) Run() error {
        _, err := fmt.Fprintln(o.streams.Out, o.cmd.Use)
        return err
}
