// Code generated by kubectl-plugin-builder; DO NOT EDIT.
{{ .SourceHeaderLicense }}
package {{ .CommandName }}

import (
        "github.com/spf13/cobra"

        "k8s.io/cli-runtime/pkg/genericclioptions"
        "{{ .PackageName }}/internal/cmd"
        {{- range .Children }}
        "{{ $.PackageName }}/{{ .DefPath }}"
        {{- end }}
)

var (
        // {{ .CommandName }}OutputModeFlag provides 
        // user-passed option to options.
        {{ .CommandName }}OutputModeFlag string

        {{- range .Flags }}
        {{ $.CommandName }}{{ .Name }}Flag {{ .Type }}
        {{- end }}
)

// WARNING: don't rename this function.
func NewCommand(streams *genericclioptions.IOStreams) *cobra.Command {
        c := &cobra.Command{
                Use:  "{{ .CommandName }}",

                Aliases: []string {
                {{- range .Aliases }}
                        "{{ .Name }}",
                {{- end }}
                },

                {{- if ne .Short "" }}
                Short: "{{ .Short }}",
                {{- end }}

                {{- if ne .Long "" }}
                Long: "{{ .Long }}",
                {{- end }}

                RunE: func(cmd *cobra.Command, args []string) error {
                        o := &options{streams: streams}
                        if err := o.Complete(cmd, args); err != nil {
                                return err
                        }

                        if err := o.Validate(); err != nil {
                                return err
                        }

                        return o.Run()
                },
        }

        hangChildrenOnCommand(c, streams)
        defineCommandFlags(c)

        return c
}

// hangChildrenOnCommand enumerates command's children and attach them into it.
func hangChildrenOnCommand(c *cobra.Command, streams *genericclioptions.IOStreams) {
        {{- range .Children }}
        c.AddCommand({{ .Name }}.NewCommand(streams))
        {{- end }}
}

// defineCommandFlags declares primitive flags.
func defineCommandFlags(c *cobra.Command) {
        c.Flags().StringVarP(
                &{{ .CommandName }}OutputModeFlag,
                "output",
                "o",
                cmd.OutputModeNormal,
                "the command's output mode",
        )

        {{- range .Flags }}
        c.Flags().{{ .UpperType }}Var(
                &{{ $.CommandName }}{{ .Name }}Flag,
                "{{ .Name }}",
                {{ .DefaultValue }},
                "{{ .Description }}",
        )
        {{- end }}
}