// Code generated by kubectl-plugin-builder.
{{ .SourceHeaderLicense }}
package cmd

import (
        "github.com/spf13/cobra"
)

type CLINodeOptions interface {
        Complete(cmd *cobra.Command, args []string) error
        Validate() error
        Run() error
}

type OutputMode = string

const (
        OutputModeNormal OutputMode = "normal"
        // OutputModeJSON
        // OutputModeYAML
)